### ISSUE TITLE
No 3.0 schema source

### ISSUE THREAD

**Issue by aaronhaddad** [circularfashion/cf-circularity-id-standard#15]
I can't find the v3.0 schema anywhere in the repo! Is this normal?

**Comment by DfromM** [comment]
Hello, thanks for your question. This is true, currently there is no v3.0 schema in this repository. We are planning to update this soon. Until then, please refer to our [circularity.id](https://circularity.id/open-data-standard.html) website instead.

**Comment by DfromM** [comment]
Documentation is updated, information on version 3 and the current version 4 as well as corresponding example files can now be found in the repository.
